apiVersion: apps/v1
kind: Deployment
metadata:
  name: springlearning
  labels:
    app: springlearning
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springlearning
  template:
    metadata:
      labels:
        app: springlearning
    spec:
      containers:
        - name: springlearning
          image: springlearning-spring-app:latest
          ports:
            - containerPort: 8080
#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8080
#            initialDelaySeconds: 10
#            periodSeconds: 10
#          livenessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8080
#            initialDelaySeconds: 20
#            periodSeconds: 20
